apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghumo-duniya-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ghumo-duniya
  template:
    metadata:
      labels:
        app: ghumo-duniya
    spec:
      containers:
      - name: ghumo-duniya-container
        image: ghumo-duniya:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ghumo-duniya-service
spec:
  type: NodePort
  selector:
    app: ghumo-duniya
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
